package edu.bellevue.cis530.week5.entity;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;


@Entity
@Builder
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "student_profiles")
public class StudentProfile {
    // profile id is the field generated by mySql
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // student phone number, must be a phone number in the format of xxx-xxx-xxxx
    @NotNull
    @NotBlank
    @Pattern(regexp = "^\\d{3}-\\d{3}-\\d{4}$",
    message = "Phone number must be in the correct format")
    private String phone;

    // student address
    @NotBlank
    private String address;

    // student address's city
    @NotBlank
    private String city;

    // student address's state code, length must be exactly 2 characters
    @NotNull
    @NotBlank
    @Size(min = 2, max = 2)
    private String state;

    // student address's zip code, must be 5 digits
    @NotNull
    @NotBlank
    @Pattern(regexp = "^[0-9]{5}$",
    message = "Zip code must be 5 characters of only numbers")
    private String zip;

    // student's emergency contact name
    @NotBlank
    private String emergencyContactName;

    // student's emergency contact number, must be a phone number in format of xxx-xxx-xxxx
    @NotBlank
    @Pattern(regexp = "^\\d{3}-\\d{3}-\\d{4}$",
            message = "Phone number must be in the correct format")
    private String emergencyContactPhone;

    // Student is the entity that owns the one-to-one relationship, specifically the field
    // "profile_id"
    @NotNull
    @JsonBackReference
    @OneToOne(mappedBy = "profile")
    private Student student;
}
