package edu.bellevue.cis530.week5.entity;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;


@Entity
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "students")
public class Student {
    // student id generated by mySql
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // students first name, length must be between 2 and 50 characters
    @NotBlank
    @Size(min = 2, max = 50)
    private String firstName;

    // students last name, length must be between 2 and 50 characters
    @NotBlank
    @Size(min = 2, max = 50)
    private String lastName;

    // students email address
    @Email
    @NotBlank
    private String email;

    // students major
    @NotBlank
    private String major;

    // students grade point average, between 0.0 and 4.0
    @NotNull
    @DecimalMin("0.0")
    @DecimalMax("4.0")
    private Float gpa;

    // year the student enrolled in, between 2000 and current year
    @NotNull
    @Min(2000)
    @Max(2026)
    private int enrollmentYear;

    // student profile is the profile entity that is owned by the student, cascade all
    @JsonManagedReference
    @JoinColumn(name = "profile_id", nullable = false)
    @OneToOne(cascade = CascadeType.ALL, orphanRemoval = true)
    private StudentProfile profile;
}
