package edu.bellevue.cis530.week5.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.*;

import java.math.BigInteger;

@Entity
@Builder
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class StudentProfile {
    // profile id is the field generated by mySql
    @Id
    @Column(name = "profile_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private BigInteger profileId;

    @NotNull
    @NotBlank
    @Size(min = 13, max = 13)
    private String phoneNumber;

    @NotNull
    @NotBlank

    private String address;

    @NotNull
    @NotBlank
    @Size(min = 2, max = 2)
    private String state;

    @NotNull
    @NotBlank
    @Size(min = 5, max = 5)
    private String zip;

    @NotBlank
    @Column(name = "emergency_contact_name", nullable = false)
    private String emergencyContactName;

    @NotBlank
    @Column(name = "emergency_contact_phone", nullable = false)
    private String emergencyContactPhone;

    // Student is the entity that owns the one-to-one relationship, specifically the field
    // "profile_id"
    @OneToOne(mappedBy = "profile_id")
    private Student student;
}
